server:
  port: 8855

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./blogapp
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  jwt:
    secret: AVeryLongAndComplexSecretKeyForJWTAuthenticationThatIsAtLeast32Bytes
    expiration:
      minutes: 60